FROM amazoncorretto:11-alpine

WORKDIR /app

ENV PROFILES=dev

ARG ORIGINAL_JAR_FILE=./build/libs/funding-service-1.0.0.jar

COPY ${ORIGINAL_JAR_FILE} funding-service.jar

CMD ["java", "-Dspring.profiles.active=${PROFILES}", "-jar", "/app/funding-service.jar"]
