-- H2 2.1.214;
SET DB_CLOSE_DELAY -1;        
;             
CREATE USER IF NOT EXISTS "SA" SALT 'c7f67460785ce3aa' HASH 'c51f2bc46f12033341d0bec2226ab5084e15fee9f479bac50d650d623c250052' ADMIN;         
CREATE MEMORY TABLE "PUBLIC"."funding"(
    "funding_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "funding_is_refundable" BOOLEAN NOT NULL,
    "funding_lotdeal_discount_amount" BIGINT NOT NULL,
    "funding_membership_discount_amount" BIGINT NOT NULL,
    "funding_privacy_agreement" BOOLEAN NOT NULL,
    "funding_status" CHARACTER VARYING(255) NOT NULL,
    "funding_support_amount" BIGINT NOT NULL,
    "funding_supporter_email" CHARACTER VARYING(255) NOT NULL,
    "funding_total_amount" BIGINT NOT NULL,
    "funding_used_point" BIGINT NOT NULL,
    "member_id" BIGINT NOT NULL,
    "project_id" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."funding" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("funding_id");              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.funding; 
CREATE MEMORY TABLE "PUBLIC"."product_funding"(
    "product_funding_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "product_funding_price" BIGINT,
    "product_funding_quantity" BIGINT,
    "product_id" BIGINT NOT NULL,
    "funding_id" BIGINT
);              
ALTER TABLE "PUBLIC"."product_funding" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("product_funding_id");              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.product_funding;         
CREATE MEMORY TABLE "PUBLIC"."supporter_with_us"(
    "supporter_with_us_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "supporter_with_us_is_amount_public" BOOLEAN NOT NULL,
    "supporter_with_us_is_name_public" BOOLEAN NOT NULL,
    "funding_id" BIGINT
);    
ALTER TABLE "PUBLIC"."supporter_with_us" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("supporter_with_us_id");          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.supporter_with_us;       
ALTER TABLE "PUBLIC"."product_funding" ADD CONSTRAINT "PUBLIC"."FKbmy9l2ovant05myebodh7pt3v" FOREIGN KEY("funding_id") REFERENCES "PUBLIC"."funding"("funding_id") NOCHECK;   
ALTER TABLE "PUBLIC"."supporter_with_us" ADD CONSTRAINT "PUBLIC"."FK4baceon1ekp4ejgsm4sivuveo" FOREIGN KEY("funding_id") REFERENCES "PUBLIC"."funding"("funding_id") NOCHECK; 
